Fixed issues with centering and generating pdf raport
AGH-Drone-Engineering/droniada-control pull request #19
Opened 2023-04-24 20:19 UTC by atomwoz

2023-04-24 20:23 UTC, Carbon225 requested changes

2023-04-24 20:23 UTC, Carbon225 commented on src/components/MapCenter.js
> +  });
To się włączy tylko raz. Chyba nie tak ma być.

2023-04-24 20:45 UTC, atomwoz commented on src/components/MapCenter.js
> +  });
To tak ma być, bo myślałem że gdy  już załaduje się mapa w miejscu innym niż defaultowy to wtedy już żeby można było swobodnie się poruszać, usuwać punkty itp bez teleportacji spowrotem, to w ten sposób blokuje to.

A drugi warunek gdy w panelu admina ustawiam dbname to wtedy on zawsze będzie sie teleportował.

2023-04-24 20:45 UTC, atomwoz commented on src/components/MapCenter.js
> +  });
Nie za bardzo wiedziałem jak inaczej to napisać

2023-04-24 21:40 UTC, Carbon225 commented on src/components/MapCenter.js
> +  });
Według mnie ten if zawsze będzie true.
Czyli jest to to samo co po prostu useEffect panMap.

2023-04-25 15:54 UTC, Carbon225 approved these changes

2023-04-25 15:56 UTC, merged